### ISSUE TITLE
Github Actions 回らない問題

### ISSUE THREAD

**Issue by RyodoTanaka** [surpace0924/coding_style_check_test#1]
.github/workflow/c-cpp.yml
上記の設定値が上手く行かない．
具体的には，git remote set-url hoge huga というコマンドで失敗している．
直したい．

**Comment by surpace0924** [comment]
GITHUB_TOKENに与えるパーミッションを指定していなかったのが原因でした。
https://docs.github.com/ja/actions/using-jobs/assigning-permissions-to-jobs
b481e98 にて修正
